### ISSUE TITLE
更新后报错，加载失败

### ISSUE THREAD

**Issue by czcz1024** [juehackr/comfyui_fk_server#27]
未检测到NodeJs，你可以在 D:\ai\ComfyUI\custom_nodes\comfyui_fk_server\server/node.txt 文件中写入node程序路径，手动配置NodeJs路径
Traceback (most recent call last):
  File "D:\ai\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\ComfyUI\custom_nodes\comfyui_fk_server\__init__.py", line 4, in <module>
    from .server import  Cancelled
  File "D:\ai\ComfyUI\custom_nodes\comfyui_fk_server\server.py", line 105, in <module>
    os.remove(config_path)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'D:\\ai\\ComfyUI\\custom_nodes\\comfyui_fk_server\\server/data.json'

**Comment by cadsoho** [comment]
我也是碰到同样问题，还以为是别的插件冲突。。。

**Comment by zk495539792** [comment]
+1

**Comment by juehackr** [comment]
解决了

**Comment by lanelead** [comment]
> 解决了

如何解决的？
